HDMS/ACMS/urls.py
from django.conf.urls import url
from . import views

app_name = "ACMS"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.index, name='login_index'),
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^workpage/$', views.workpage, name='workpage'),
    url(r'^workpage/patient/$', views.patient, name = 'patient'),


]

HDMS/HDMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

admin.site.site_header = "HDMS Administration"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^acms/', include('ACMS.urls') ),
]

HDMS/ACMS/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from datetime import  date
from django.contrib.auth.models import User


# Create your models here.
class hmo_list(models.Model):
    name = models.CharField(max_length = 200)
    mobile = models.CharField(max_length = 100, null = True, blank = True)
    email = models.EmailField(help_text = "Please enter a valid email address!", blank=True, default="no-email@domain.com")
    address = models.TextField(default="NIL")
    hmo_status = models.BooleanField('Hmo Status', help_text = 'uncheck if HMO is not active', default = '0')
    date_added = models.DateTimeField(default=timezone.now)
    added_by = models.ForeignKey(User, default = User.objects.get(username = "Admin").id)

    def __str__(self):
        return self.name

class state(models.Model):
    state_name = models.CharField("Name of State", max_length=15)

    def __str__(self):
        return ("%s" % self.state_name)

class patient(models.Model):
    surname = models.CharField(max_length = 20)
    firstname = models.CharField(max_length = 20)
    othernames = models.CharField(max_length= 20, null=True, default="NIL")
    card_no = models.CharField(max_length = 15)
    gender = models.CharField(max_length = 1, choices=(("M", "Male"), ("F", "Female")), default="M")
    phone_number = models.CharField(max_length = 15, default="NIL")
    address = models.CharField(max_length = 50, default="NIL")
    hmo = models.ForeignKey(hmo_list,verbose_name="hmo_id", default= 0)
    date_added = models.DateTimeField(default=timezone.now)
    added_by = models.ForeignKey(User, default = User.objects.get(username = "Admin").id)
    origin = models.ForeignKey(state, default = state.objects.get(state_name = "OTHERS").id)


    def __str__(self):
        return ("%s %s" % (self.surname, self.firstname)).upper()

class drug(models.Model):
    drug_name = models.CharField(max_length=50)
    drug_code = models.CharField(max_length=15)
    date_added = models.DateTimeField(default=timezone.now)
    added_by = models.ForeignKey(User, default = User.objects.get(username = "Admin").id)

    def __str__(self):
        return  ("%s" % self.drug_name).upper()

HDMS/ACMS/forms.py
from django import forms
from models import state, hmo_list, patient

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length = 20)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

class PatientForm(forms.Form):
    attributes = {'class' : 'form-control'}
    surname = forms.CharField(max_length=15, required= True, widget= forms.TextInput(attrs= attributes))
    firstname = forms.CharField(max_length= 15, required= True, widget= forms.TextInput(attrs= attributes))
    othername = forms.CharField(max_length= 15, required= True, widget= forms.TextInput(attrs= attributes))
    cardNo = forms.CharField(max_length=15, required=True, widget= forms.TextInput(attrs= attributes))
    gender = forms.ChoiceField(choices= (("M", "Male"), ("F", "Female")), initial= "M", widget= forms.Select(attrs=attributes))
    mobileNo = forms.CharField(required=True, widget= forms.TextInput(attrs= attributes))
    address = forms.CharField(required= True, widget= forms.TextInput(attrs= attributes))
    origin = forms.ModelChoiceField(required=True, widget=forms.Select(attrs=attributes), queryset= state.objects.order_by("state_name"), empty_label="Select a State")
    hmo = forms.ModelChoiceField(required=True, widget=forms.Select(attrs=attributes), queryset= hmo_list.objects.order_by("name"), empty_label= "Select an HMO")

    def __init__ (self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(PatientForm, self).__init__(*args, **kwargs)

    def __str__(self):
        data = self.cleaned_data
        return ("%s %s with card number: %s has been created" % (data['surname'], data['firstname'], data['cardNo']))


    def save (self):
        data = self.cleaned_data
        new_patient = patient(surname = data['surname'], firstname = data['firstname'], othernames = data['othername'],                              card_no = data['cardNo'], gender = data['gender'], phone_number = data['mobileNo'],                                  address = data['address'], hmo = data['hmo'], added_by = self.user,
                              origin = data['origin'])
        new_patient.save()

HDMS/ACMS/views.py
from django.shortcuts import render, get_object_or_404
from .forms import LoginForm, PatientForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth import hashers


# Create your views here.

login_url = '/acms/login'

def index(request):
    if request.method == "POST": # checking if it's a post request
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username = form.cleaned_data['username'], password = form.cleaned_data['password'])
            if user is not None:
                if user.is_active: # checking if the user is still active
                    login(request, user) # logging the user in
                    request.session.set_expiry(1800) # setting the session expiry time, after which login is required
                    return HttpResponseRedirect(reverse('ACMS:homepage'))

            else:
                try:
                    username = User.objects.get(username = form.cleaned_data["username"])
                    # since authenticate method returns none for inactive registered users, the if statement below takes care of checking if user exist
                    # but inactive in order to forward the right feedback message
                    if username and hashers.check_password(form.cleaned_data["password"], User.objects.get(username = username).password):
                        messages.error(request, "Your account has been disabled! Contact Admin...")
                        return HttpResponseRedirect(reverse('ACMS:index'))
                    else:
                         messages.error(request, 'Incorrect username and password!!!') # saving message error to be displayed on template
                         return HttpResponseRedirect(reverse('ACMS:index'))
                except:
                    messages.error(request, 'Incorrect username and password!!!') # saving message error to be displayed on template
                    return HttpResponseRedirect(reverse('ACMS:index'))

# if the request is a GET request
    else:
        form = LoginForm() # creating new form
        if request.path == "/acms/login/":
            messages.info(request, "Please log in");
        logout(request) # logging out the user and clearing the user's session

    return render(request, 'acms/index.html', {"form": form})



@login_required(redirect_field_name="", login_url=login_url) # login required to view this page
def homepage(request):
    admin = False
    if request.user.is_staff: admin = True # checking if the user has administrative rights
    context = {"name" : "%s %s" % ( request.user.first_name, request.user.last_name), "username" : request.user.username, "admin" : admin} # declaring the template context
    return render(request, 'acms/homepage.html', context) # rendering the homepage template

@login_required(redirect_field_name="", login_url=login_url)
def workpage(request):
    admin = False
    if request.user.is_staff: admin = True
    patient_form = PatientForm(auto_id= False)
    context = {"name" : "%s %s" % (request.user.last_name, request.user.first_name), "username" : request.user.username, 'admin': admin, "patient_form" : patient_form}
    return render(request, 'acms/workpage.html', context)

@login_required(redirect_field_name = "", login_url = login_url)
def patient(request):
    if request.method == 'POST': # checking the request method
        patient_form = PatientForm(request.POST, user = request.user)
        if patient_form.is_valid():
            patient_form.save()
            messages.success(request, str(patient_form))
            return HttpResponseRedirect(reverse('ACMS:workpage'))
        else:
            messages.error(request, "Patient couldn't be created")
            return HttpResponseRedirect(reverse('ACMS:workpage'))
    else:
        return HttpResponseRedirect(reverse('ACMS:workpage'))

HDMS/ACMS/templates/ACMS/archive.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>HDMS</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'ACMS/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'ACMS/css/landing-page.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'ACMS/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">HDMS</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Header -->
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>HMO DATA MANAGEMENT SYSTEM</h1>
                        <h3>ACMS</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <button id="loginFormToggleButton" class="btn btn-default btn-lg" data-toggle="modal" data-target="#loginModal"><span class="network-name">lOGIN</span></button>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- login form modal -->
    <div class="modal fade" {% if messages %} id="loginModalJs" {% else %} id="loginModal"{% endif %}  tabindex="-1" role="dialog" aria-labelledby="modalLabel" data-backdrop ="static" >
      <div  class="modal-dialog " role="document">
        <div class="modal-content">
          <div class="modal-header" style="text-align:center">
            <button type="button" name="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 id="modalLabel">Login</h4>
          </div><!-- modal-header -->
          <div class="modal-body">
              {% if messages %}
                <div id="loginErrorAlert" class="alert fade in alert-danger alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        {{ message }}
                    {% endif %}
                  {% endfor %}
                </div>
              {% endif %}
            <form class="form-horizontal" action="{% url 'ACMS:index' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">Username</label>
                    <div class="controls col-sm-10">
                      <input name="username" type="text" value="" class="form-control login-input " id="username" placeholder="Username" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">Password</label>
                    <div class="controls col-sm-10">
                      <input name="password" type="password" value="" class="form-control login-input" id="password" placeholder="Password" required>
                    </div>
                </div>
                <div class="form-group">
                    <div style="text-align: right;" class="col-sm-10 col-sm-offset-2" >
                       <input style="width: 100%" class= "btn btn-primary" type="submit" value="login" >
                       <p> <a href="#"  style="color: red" >Forgot Password?</a> </p>
                    </div>
                </div>


            </form>
          </div><!-- modal-body -->

        </div><!-- modal-content -->
      </div><!-- modal-dialog -->
    </div><!-- modal -->
    <!-- end of login form modal -->

    <!-- Page Content -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-xs-12">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Osuntuyi Medical Centre</h2>
                    <p class="lead">We Care, Christ Heals</p>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Connect to OMC:</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">HDMS</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Osuntuyi Medical Centre 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'ACMS/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'ACMS/js/bootstrap.min.js' %}"></script>

     <!-- custom javascript -->
    <script src="{% static 'ACMS/js/acms.js' %}"></script>



</body>

</html>

HDMS/ACMS/templates/ACMS/workpage.html
{% extends 'ACMS/homepage.html' %}
{% load staticfiles %}

{% block title %}
    <title>Workpage</title>
{% endblock title %}

{% block bootstrap %}
    {{block.super}}
    <!-- Simple-sidebar  CSS -->
    <link href="{% static 'ACMS/css/simple-sidebar.css' %}" rel="stylesheet" />
{% endblock bootstrap %}



{% block content %}
     <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">Home  </a>
                </li>
                <li>
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                      <!-- patient panel -->
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="dashboard">
                              <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#dashboard-submenu" aria-expanded="true" aria-controls="dashboard-submenu">
                                  Dashboard
                                </a>
                              </h4>
                            </div>
                            <div id="dashboard-submenu" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="dashboard">
                              <div class="list-group">

                              </div>
                            </div>
                        </div>
                      <!-- patient panel -->
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="patient">
                              <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#patient-submenu" aria-expanded="true" aria-controls="patient-submenu">
                                  Patient
                                </a>
                              </h4>
                            </div>
                            <div id="patient-submenu" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="patient">
                              <div class="list-group">
                                <ul>
                                    <li><a id="addPatient"  role="button" data-toggle="modal" data-target="#patientModalForm">Add Patient</a></li>
                                    <li><a href="#">Find Patient</a></li>
                                </ul>
                              </div>
                            </div>
                        </div>
                      <!-- drug panel -->
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="drug">
                              <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#drug-submenu" aria-expanded="false" aria-controls="drug-submenu">
                                  Drugs
                                </a>
                              </h4>
                            </div>
                            <div id="drug-submenu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="drug">
                              <div class="list-group">
                                <ul>
                                    <li><a role="button" data-toggle="modal" data-target="#drugForm">Add Drug</a></li>
                                    <li><a href="#">Find Drug</a></li>
                                </ul>
                              </div>
                            </div>
                        </div>
                      <!-- authorization code panel -->
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="authorization-code">
                              <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#authorization-code-submenu" aria-expanded="false" aria-controls="authorization-code-submenu">
                                  Authorization Code
                                </a>
                              </h4>
                            </div>
                            <div id="authorization-code-submenu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="authorization-code">
                              <div class="list-group">
                               <ul>
                                    <li><a href="#">Add Authorization Code</a></li>
                                    <li><a href="#">Find Authorization Code</a></li>
                                </ul>
                              </div>
                           </div>
                      <!-- hmo panel -->
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="hmo">
                              <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#hmo-submenu" aria-expanded="false" aria-controls="hmo-submenu">
                                  HMO
                                </a>
                              </h4>
                            </div>
                            <div id="hmo-submenu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="hmo">
                              <div class="list-group">
                                <ul>
                                    <li><a href="#">Add HMO</a></li>
                                    <li><a href="#">Find HMO</a></li>
                                </ul>
                              </div>
                            </div>
                        </div>
                      <!-- backup panel -->
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="backup">
                              <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#backup-submenu" aria-expanded="false" aria-controls="backup-submenu">
                                  Backup
                                </a>
                              </h4>
                            </div>
                            <div id="backup-submenu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="backup">
                              <div class="list-group">
                               <ul>
                                    <li><a href="#">Create Backup</a></li>
                                    <li><a href="#">Restore Backup</a></li>
                                </ul>
                              </div>
                            </div>
                        </div>
                    </div>

                </li>
               
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Simple Sidebar</h1>
                        <p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
                        <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
                        
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->


<!-- patient form -->
<div class="modal fade" id="patientModalForm" tabindex="-1" role="dialog" aria-labelledby="modalLabel" data-backdrop ="static" >
      <div  class="modal-dialog " role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" name="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 id="modalLabel">New Patient</h4>
          </div><!-- modal-header -->
          <div class="modal-body">
             <form id="patientForm" action="{% url 'ACMS:patient' %}" method="post">
                 {% csrf_token %}
              <div class="form-group">
                <label for="surname">Surname<span id="required">*</span></label>
                  {{ patient_form.surname }}
              </div>
              <div class="form-group">
                <label for="firstname">Firstname<span id="required">*</span></label>
                {{ patient_form.firstname }}
              </div>
              <div class="form-group">
                <label for="othername">Othername<span id="required">*</span></label>
                {{ patient_form.othername }}
              </div>
              <div class="form-group">
                <label for="cardNo">Card No<span id="required">*</span></label>
                {{ patient_form.cardNo }}
              </div>
              <div class="form-group">
                <label for="gender">Gender<span id="required">*</span></label>
                    {{ patient_form.gender }}
              </div>
               <div class="form-group">
                <label for="mobile">Mobile<span id="required">*</span></label>
                {{ patient_form.mobileNo }}
              </div>
              <div class="form-group">
                <label for="hmo">HMO<span id="required">*</span></label>
                {{ patient_form.hmo }}
              </div>
              <div class="form-group">
                <label for="origin">State of Origin<span id="required">*</span></label>
                {{ patient_form.origin }}
              </div>
              <div class="form-group">
                <label for="address">Address<span id="required">*</span></label>
                {{ patient_form.address }}
              </div>
              <div class="form-group">
                  <input style="width: 100%" class= "btn btn-danger" type="submit" value="Submit" >
              </div>
            </form>
          </div><!-- modal-body -->
        </div><!-- modal-content -->
      </div><!-- modal-dialog -->
</div><!-- modal -->
<!-- end of patient modal form -->

<!-- drug form -->
<div class="modal fade" id="drugForm" tabindex="-1" role="dialog" aria-labelledby="modalLabel" data-backdrop ="static" >
      <div  class="modal-dialog " role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" name="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 id="modalLabel">New Drug</h4>
          </div><!-- modal-header -->
          <div class="modal-body">
             <form action="{% url 'ACMS:index' %}" method="post">
                 {% csrf_token %}
              <div class="form-group">
                <label for="username">Username</label>
                <input name="username" type="text" class="form-control" id="username" required="true">
              </div>
              <div class="form-group">
                <label for="password">Password</label>
                <input name="password" type="password" class="form-control" id="password" required="true" placeholder="**********">
              </div>
              <div class="form-group">
                  <input style="width: 100%" class= "btn btn-primary" type="submit" value="Log in" >
              </div>
            </form>
          </div><!-- modal-body -->
        </div><!-- modal-content -->
      </div><!-- modal-dialog -->
</div><!-- modal -->
<!-- end of drug modal form -->

<!-- alert modal -->

<div class="modal fade" {% if messages %} id="alert-modal" {% else %} id="dont-alert-modal" {% endif %} tabindex="-1" role="dialog" aria-labelledby="modalLabel" data-backdrop ="static" >
      <div  class="modal-dialog " role="document">
        <div  id="form-feedback-alert" class="alert alert-warning alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

              {% for message in messages %}
                  {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <p class="text-success"><strong>Successful</strong></p>
                  {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <p class="text-danger"><strong>Error</strong></p>
                  {% endif %}
                  <p>{{ message }}</p>
              {% endfor %}

        </div>
      </div><!-- modal-dialog -->
</div><!-- modal -->
<!-- end of alert modal  -->

{% endblock content %}

{% block footer %}
{% endblock footer %}

{% block scripts %}
    {{block.super}}
     <!-- Menu Toggle Script -->
    <script>
        $("#brandName").attr({href : "#menu-toggle", id : "menu-toggle"});
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

    </script>
{% endblock scripts %}